FileServer/views/admin_views.py
import os
import hashlib
from glob import glob
from datetime import datetime


from flask import url_for, redirect, flash, g, render_template, Blueprint, current_app, request
from sqlalchemy import and_


from .. import db
from ..models import User, File, FileAccessPermission
from .auth_views import login_required, admin_permission_required, log


bp = Blueprint("admin", __name__, url_prefix = "/admin")


@bp.route("/user/list/")
@login_required
@admin_permission_required
def user_list():
    user_list = User.query.all()
    return render_template("admin/admin_user_manage.html", user_list = user_list)


@bp.route("/user/delete/<int:user_id>/")
@login_required
@admin_permission_required
def user_delete(user_id):
    user = User.query.get(user_id)
    if not user:
        flash("잘못된 유저 아이디 입니다")
    else:
        if user.admin_permission:
            flash("관리자 계정은 삭제할 수 없습니다")
        else:
            log("계정 삭제 성공", user)
            username = user.username
            db.session.delete(user)
            db.session.commit()
            flash(f"{username} 삭제 성공!")

    return redirect(url_for(".user_list"))


@bp.route("/user/permission/<int:user_id>/<int:permission>/")
@login_required
@admin_permission_required
def user_permission(user_id, permission):
    user = User.query.get_or_404(user_id)
    if not user:
        flash("잘못된 유저 아이디입니다")
    else:
        log("권한 변경", user)
        user.permission = permission
        db.session.add(user)
        db.session.commit()

    return redirect(url_for(".user_list"))


@bp.route("/user/permission/close")
@login_required
@admin_permission_required
def user_permission_close():
    try:
        User.query.update({User.permission : 0})
        db.session.commit()
    except RuntimeError:
        flash("모든 권한 변경 실패")
        db.session.rollback()

    return redirect(url_for(".user_list"))

def toggle_file_access_permission(user_id, file_id):
    user = User.query.get(user_id)
    if not user:
        flash("잘못된 유저 아이디")
        return

    file_acc_per = FileAccessPermission.query.filter(and_(FileAccessPermission.user_id == user_id
                                                        , FileAccessPermission.file_id == file_id)).first()
    if file_acc_per:
        try:
            db.session.delete(file_acc_per)
            db.session.commit()
        except:
            db.session.rollback()
            flash("권한 설정에 실패했습니다")

        return

    try:
        file_acc_per = FileAccessPermission(user_id = user_id
                                            , file_id = file_id
                                            , create_date = datetime.now())

        db.session.add(file_acc_per)
        db.session.commit()
    except:
        flash("권한 설정에 실패했습니다")
        db.session.rollback()


@bp.route("/user/file/permission/<int:user_id>/")
@login_required
@admin_permission_required
def user_file_permission(user_id):
    file_id = request.args.get("file_id", None)
    
    if file_id:
        toggle_file_access_permission(user_id, file_id)
        return redirect(url_for(".user_file_permission", user_id = user_id))

    q = File.query.outerjoin(FileAccessPermission, and_(File.id == FileAccessPermission.file_id
                            , FileAccessPermission.user_id == user_id))\
                .add_columns(File.id, File.filename, File.size, FileAccessPermission.user_id)
    
    file_info_list = q.all()

    return render_template("admin/admin_user_file_permission.html", user_id = user_id, file_list = file_info_list)


@bp.route("/file/list/")
@login_required
@admin_permission_required
def file_list():
    file_list = File.query.all()
    return render_template("admin/admin_file_manage.html", file_list = file_list)


#https://stackoverflow.com/questions/16874598/how-do-i-calculate-the-md5-checksum-of-a-file-in-python
def md5_file_hash(file_name):
    with open(file_name, "rb") as f:
        file_hash = hashlib.md5()
        while chunk := f.read(8192):
            file_hash.update(chunk)

    return file_hash.hexdigest()


@bp.route("/file/refresh/")
@login_required
@admin_permission_required
def list_refresh():
    file_dir = current_app.config["SHARE_FILE_DIR"]
    glob_pattern = os.path.join(file_dir, "*.*")
    disk_file_list = glob(glob_pattern)
    disk_file_hash_list = list()

    for disk_file in disk_file_list:
        file_hash = md5_file_hash(disk_file)
        disk_file_hash_list.append(file_hash)

    #모두 삭제 후 
    try:
        File.query.delete()
        db.session.commit()
    except:
        db.session.rollback()

    #새로 등록
    try:
        for disk_file, file_hash in zip(disk_file_list, disk_file_hash_list):
            file = File(filename = os.path.split(disk_file)[-1]
                        , permission = 999
                        , hash = file_hash
                        , size = os.path.getsize(disk_file))
            
            db.session.add(file)

        db.session.commit()
    except:
        db.session.rollback()

    return redirect(url_for(".file_list"))


@bp.route("/permission/<int:file_id>/<int:permission>/")
def file_permission(file_id, permission):
    file = File.query.get(file_id)
    if not file:
        flash("잘못된 파일 아이디")
    else:
        file.permission = permission
        db.session.add(file)
        db.session.commit()

    return redirect(url_for(".file_list"))


@bp.route("/file/delete/<int:file_id>/")
@login_required
@admin_permission_required
def file_delete(file_id):
    file = File.query.get(file_id)
    if not file:
        flash("잘못된 파일 아이디")
        return redirect(url_for(".file_list"))

    file_dir = current_app.config["SHARE_FILE_DIR"]
    file_path = os.path.join(file_dir, file.filename)
    file_path = os.path.abspath(file_path)
    
    try:
        if not os.path.isfile(file_path):
            flash("존재하지 않는 파일입니다")
        else:
            os.remove(file_path)

        db.session.delete(file)
        db.session.commit()
    except Exception as e:
        flash("파일 삭제에 실패했습니다")
        db.session.rollback()

    return redirect(url_for(".file_list"))


@bp.route("/file/upload/", methods = ["GET", "POST"])
@login_required
@admin_permission_required
def file_upload():
    if request.method == "POST":
        if "form-file" not in  request.files:
            flash("잘못된 파일입니다")
            return redirect(url_for(".file_list"))

        file = request.files["form-file"]
        if file.filename == "":
            flash("파일이 선택되지 않았습니다")
            return redirect(url_for(".file_list"))

        if file:
            file_dir = current_app.config["SHARE_FILE_DIR"]
            filename = os.path.split(file.filename)[-1]

            file_path = os.path.join(file_dir, filename)
            file_path = os.path.abspath(file_path)

            file.save(file_path)

            file_hash = md5_file_hash(file_path)
            file = File(filename = filename
                        , hash = file_hash
                        , size = os.path.getsize(file_path)
                        , permission = 999)

            db.session.add(file)
            db.session.commit()
            return redirect(url_for(".file_list"))

    flash("잘못된 요청")
    return redirect(url_for(".file_list"))

FileServer/views/auth_views.py
import functools
from datetime import datetime
from operator import or_, and_


from flask import Blueprint, render_template, request, url_for, session, g, flash
from werkzeug.utils import redirect
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy import or_

from FileServer import db
from FileServer.models import FileAccessPermission, User, UserLog, File
from FileServer.forms import LoginForm, SignupForm


bp = Blueprint("auth", __name__, url_prefix="/auth")


def log(message, user):
    try:
        user_log = UserLog(user_id = user.id, level = 20, type = 0
                , message = f"user id : {user.id}, username : {user.username} {message}"
                , create_date = datetime.now())
        db.session.add(user_log)
        db.session.commit()
    except:
        db.rollback()

def auth_log(message, user = None):
    def Inner(view):
        @functools.wraps(view)
        def wrapper(*args, **kwargs):
            user_ = user if user else g.user
            log(message, user_)
            return view(*args, **kwargs)
        return wrapper
    return Inner


@bp.route("/")
def index():
    return redirect(url_for('.login'))


@bp.route("/login/", methods = ("GET", "POST"))
def login():
    form = LoginForm()
    if request.method == "POST" and form.validate_on_submit():
        error = None
        user = User().query.filter_by(username = form.username.data).first()
        if not user:
            error = "등록된 유저가 없습니다"
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 일치하지 않습니다"
        
        if error is None:
            session.clear()
            session["user_id"] = user.id
            _next = request.args.get("next", "")
            log("로그인 성공", user)
            if _next:
                return redirect(_next)

            return redirect(url_for("main.index"))

        flash(error)
    return render_template("auth/login.html", form = form)


@bp.route("/logout/")
@auth_log("로그아웃 성공")
def logout():
    session.clear()
    return redirect(url_for("main.index"))


@bp.route("/signup/", methods = ("GET", "POST"))
def signup():
    form = SignupForm()
    if request.method == "POST" and form.validate_on_submit():
        user = User().query.filter(or_(User.username == form.username.data, User.email == form.email.data)).first()
        if not user:
            user = User(username = form.username.data
                        , password = generate_password_hash(form.password1.data)
                        , email = form.email.data
                        , admin_permission = 0
                        , permission = 0
                        , create_date = datetime.now())


            db.session.add(user)
            db.session.commit()

            log("회원 가입", user)
            return redirect(url_for('.login'))
        
        flash("이미 존재하는 유저입니다")
    return render_template("auth/signup.html", form = form)


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get("user_id")
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == "GET" else ""
            return redirect(url_for("auth.login", next = _next))

        return view(*args, **kwargs)

    return wrapped_view


def admin_permission_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if not g.user.admin_permission:
            flash("권한이 부족합니다")
            user = g.user
            log("잘못된 접근(관리자 페이지 접근 시도)", user)
            return redirect(url_for("main.index"))

        return view(*args, **kwargs)

    return wrapped_view

FileServer/views/file_views.py
import os
import functools
from pathlib import Path
from glob import glob
from datetime import datetime


from flask import Blueprint, flash, redirect, render_template, request, send_file, g, current_app, url_for
from werkzeug.utils import secure_filename
from sqlalchemy import or_, and_


from .auth_views import login_required, admin_permission_required
from ..models import File, FileAccessLog, FileAccessPermission
from .. import db


bp = Blueprint("file", __name__, url_prefix = "/file")


def log(file_id):
    try:
        user = g.user
        file = File.query.get(file_id)
        file_log = FileAccessLog(user_id = user.id
                        , file_id = file.id
                        , file_name = file.filename
                        , create_date = datetime.now())

        db.session.add(file_log)
        db.session.commit()
    except:
        db.session.rollback()


def file_log(view):
    @functools.wraps(view)
    def wrapper(*args, **kwargs):
        log(kwargs["file_id"])
        return view(*args, **kwargs)
    return wrapper


@bp.route("/list/")
@login_required
def _list():
    if g.user.admin_permission:
        file_list = File.query.all()
    else:
        file_list = File.query.join(FileAccessPermission)\
                        .filter(and_(FileAccessPermission.user_id == g.user.id, File.permission < g.user.permission)).all()

    return render_template("file/file_list.html", file_list = file_list)


@bp.route("/down/<int:file_id>/")
@login_required
@file_log
def down(file_id):
    user = g.user

    if not user.admin_permission:
        user_access_filter = and_(FileAccessPermission.user_id == user.id
                            , FileAccessPermission.file_id == file_id)
        access_filter = and_(user_access_filter , user.permission > File.permission)
        
        file = File.query.join(FileAccessPermission)\
                    .filter(access_filter).first()

        if not file:
            return render_template("404.html")
    else:
        file = File.query.get_or_404(file_id)

    file_dir = current_app.config["SHARE_FILE_DIR"]
    file_path = os.path.join(file_dir, file.filename)
    
    if not os.path.exists(file_path):
        return render_template("404.html")

    return send_file(file_path)

FileServer/templates/base.html
<!doctype html>
<html lang="ko">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
            rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <!-- Bootstrap JS -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

        <!-- JQuery -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>

        <title>게두링</title>
    </head>
<body>
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">게두링</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if g.user %}
            <ul class="navbar-nav">
                {% if g.user.admin_permission%}
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('admin.user_list') }}">사용자 관리</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('admin.file_list') }}">파일 관리</a>
                </li>
                {% endif %}
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('file._list') }}">파일</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                </li>
            </ul>
            {% endif%}
        </div>
    </div>
</nav>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

FileServer/templates/flash_errors.html
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

FileServer/templates/form_errors.html
<!-- 필드오류 -->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
{% include "flash_errors.html" %}