FileServer/views/file_views.py
import os
import functools
from pathlib import Path
from glob import glob
from datetime import datetime


from flask import Blueprint, flash, redirect, render_template, request, send_file, g, current_app, url_for
from werkzeug.utils import secure_filename
from sqlalchemy import or_, and_


from .auth_views import login_required, admin_permission_required
from ..models import File, FileAccessLog, FileAccessPermission
from .. import db


bp = Blueprint("file", __name__, url_prefix = "/file")


def log(file_id):
    try:
        user = g.user
        file = File.query.get(file_id)
        file_log = FileAccessLog(user_id = user.id
                        , file_id = file.id
                        , file_name = file.filename
                        , create_date = datetime.now())

        db.session.add(file_log)
        db.session.commit()
    except:
        db.session.rollback()


def file_log(view):
    @functools.wraps(view)
    def wrapper(*args, **kwargs):
        log(kwargs["file_id"])
        return view(*args, **kwargs)
    return wrapper


@bp.route("/list/")
@login_required
def _list():
    if g.user.admin_permission:
        file_list = File.query.all()
    else:
        file_list = File.query.join(FileAccessPermission)\
                        .filter(and_(FileAccessPermission.user_id == g.user.id, File.permission < g.user.permission)).all()

    return render_template("file/file_list.html", file_list = file_list)


@bp.route("/down/<int:file_id>/")
@login_required
@file_log
def down(file_id):
    user = g.user

    if not user.admin_permission:
        user_access_filter = and_(FileAccessPermission.user_id == user.id
                            , FileAccessPermission.file_id == file_id)
        access_filter = and_(user_access_filter , user.permission > File.permission)
        
        file = File.query.join(FileAccessPermission)\
                    .filter(access_filter).first()

        if not file:
            return render_template("404.html")
    else:
        file = File.query.get_or_404(file_id)

    file_dir = current_app.config["SHARE_FILE_DIR"]
    file_path = os.path.join(file_dir, file.filename)
    
    if not os.path.exists(file_path):
        return render_template("404.html")

    return send_file(file_path)

FileServer/templates/file/file_list.html
{% extends "base.html" %}
{% block content %}
{% include "flash_errors.html" %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th class="col-sm-2">파일 크기(KB)</th>
        </tr>
        </thead>
        <tbody>
        {% if file_list %}
        {% for file in file_list %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>
                <a href="{{ url_for('file.down', file_id = file.id) }}" target="_blank">{{ file.filename }}</a>
            </td>
            <td>
                {{'%0.2f'|format(file.size/1024|float)}}KB
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">공유된 파일이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

FileServer/templates/file/file_manage.html
{% extends "base.html" %}
{% block content %}
{% include "flash_errors.html" %}
<div class="container my-3">
    <div class="d-flex justify-content-end">
        <form action="{{ url_for('file.upload') }}" method="POST" enctype = "multipart/form-data">
            <input class="form-control visually-hidden" type="file" name="form-file" id="form-file">
            <button type="submit" class="btn btn-primary visually-hidden" id="form-file-upload">전송</button>
        </form>
        <a href="javascript:void(0)" class="btn btn-sm btn-outline-primary my-3" id="upload">업로드</a>
    </div>
    <table class="table text-center">
        <thead>
        <tr class="table-dark">
            <th class="col-sm-1">번호</th>
            <th>제목</th>
            <th class="col-sm-2">파일 크기(KB)</th>
            <th class="col-sm-1">공개 여부</th>
            <th class="col-sm-1">삭제</th>
        </tr>
        </thead>
        <tbody>
        {% if file_list %}
        {% for file in file_list %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>
                <a href="{{ url_for('file.down', file_id = file.id) }}" target="_blank">{{ file.filename }}</a>
            </td>
            <td>
                {{'%0.2f'|format(file.size/1024|float)}}KB
            </td>
            <td>
                {% if file.permission %}
                <a href="{{ url_for('file._permission', file_id = file.id, permission = 0)}}" class="btn btn-sm btn-outline-secondary w-100">비공개</a>
                {% else %}
                <a href="{{ url_for('file._permission', file_id = file.id, permission = 1)}}" class="btn btn-sm btn-outline-primary w-100">공개</a>
                {% endif %}
            </td>
            <td>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-danger w-100"
                    data-uri="{{ url_for('file.delete', file_id=file.id) }}">삭제</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="5">등록된 파일이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").click(function(){
        if(confirm("정말로 삭제하시겠습니까?"))
            location.href = $(this).attr("data-uri");
    });

    //$("#form-file").hide();
    //$("#form-file-upload").hide();
    $("#form-file").change(function(){
        $("#form-file-upload").click()
    });

    $("#upload").click(function(){
        $("#form-file").click()
    });
});
</script>
{% endblock %}